//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:04:27 AM CST 
//


package com.expedia.edx.datatype;

import java.lang.Long;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.expedia.edx.datatype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TPID_QNAME = new QName("", "TPID");
    private final static QName _LanguageCode_QNAME = new QName("", "LanguageCode");
    private final static QName _MerchantID_QNAME = new QName("", "MerchantID");
    private final static QName _SupplyLocale_QNAME = new QName("", "SupplyLocale");
    private final static QName _LangId_QNAME = new QName("", "LangId");
    private final static QName _ClientLocale_QNAME = new QName("", "ClientLocale");
    private final static QName _Currency_QNAME = new QName("", "Currency");
    private final static QName _EAPID_QNAME = new QName("", "EAPID");
    private final static QName _SiteId_QNAME = new QName("", "SiteId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.expedia.edx.datatype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.expedia.edx.datatype.Poslist }
     * 
     */
    public Poslist createPoslist() {
        return new Poslist();
    }

    /**
     * Create an instance of {@link com.expedia.edx.datatype.Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.lang.Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TPID")
    public JAXBElement<Long> createTPID(Long value) {
        return new JAXBElement<Long>(_TPID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LanguageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguageCode(String value) {
        return new JAXBElement<String>(_LanguageCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.lang.Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantID")
    public JAXBElement<Long> createMerchantID(Long value) {
        return new JAXBElement<Long>(_MerchantID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupplyLocale")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSupplyLocale(String value) {
        return new JAXBElement<String>(_SupplyLocale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.lang.Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LangId")
    public JAXBElement<Long> createLangId(Long value) {
        return new JAXBElement<Long>(_LangId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClientLocale")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createClientLocale(String value) {
        return new JAXBElement<String>(_ClientLocale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Currency")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.lang.Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAPID")
    public JAXBElement<Long> createEAPID(Long value) {
        return new JAXBElement<Long>(_EAPID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.lang.Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SiteId")
    public JAXBElement<Long> createSiteId(Long value) {
        return new JAXBElement<Long>(_SiteId_QNAME, Long.class, null, value);
    }

}
