//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 11:04:27 AM CST 
//


package com.expedia.edx.datatype;

import java.lang.Long;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SiteId"/>
 *         &lt;element ref="{}TPID"/>
 *         &lt;element ref="{}EAPID"/>
 *         &lt;element ref="{}LanguageCode"/>
 *         &lt;element ref="{}ClientLocale"/>
 *         &lt;element ref="{}LangId"/>
 *         &lt;element ref="{}Currency"/>
 *         &lt;element ref="{}MerchantID"/>
 *         &lt;element ref="{}SupplyLocale"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "siteId",
        "tpid",
        "eapid",
        "languageCode",
        "clientLocale",
        "langId",
        "currency",
        "merchantID",
        "supplyLocale"
})
@XmlRootElement(name = "pos")
public class Pos {

    @XmlElement(name = "SiteId", required = true)
    protected Long siteId;
    @XmlElement(name = "TPID", required = true)
    protected Long tpid;
    @XmlElement(name = "EAPID", required = true)
    protected Long eapid;
    @XmlElement(name = "LanguageCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String languageCode;
    @XmlElement(name = "ClientLocale", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String clientLocale;
    @XmlElement(name = "LangId", required = true)
    protected Long langId;
    @XmlElement(name = "Currency", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currency;
    @XmlElement(name = "MerchantID", required = true)
    protected Long merchantID;
    @XmlElement(name = "SupplyLocale", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String supplyLocale;

    /**
     * Gets the value of the siteId property.
     *
     * @return possible object is
     * {@link java.lang.Long }
     */
    public Long getSiteId() {
        return siteId;
    }


    /**
     * Gets the value of the tpid property.
     *
     * @return possible object is
     * {@link java.lang.Long }
     */
    public Long getTPID() {
        return tpid;
    }


    /**
     * Gets the value of the eapid property.
     *
     * @return possible object is
     * {@link java.lang.Long }
     */
    public Long getEAPID() {
        return eapid;
    }


    /**
     * Gets the value of the languageCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLanguageCode() {
        return languageCode;
    }


    /**
     * Gets the value of the clientLocale property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClientLocale() {
        return clientLocale;
    }


    /**
     * Gets the value of the langId property.
     *
     * @return possible object is
     * {@link java.lang.Long }
     */
    public Long getLangId() {
        return langId;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrency() {
        return currency;
    }


    /**
     * Gets the value of the merchantID property.
     *
     * @return possible object is
     * {@link java.lang.Long }
     */
    public Long getMerchantID() {
        return merchantID;
    }


    /**
     * Gets the value of the supplyLocale property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSupplyLocale() {
        return supplyLocale;
    }

}
